// <auto-generated />
using System;
using HRMaster_API_Project.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMaster_API_Project.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240820131826_ınitdbCurrencyAdvanceRequest")]
    partial class ınitdbCurrencyAdvanceRequest
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.AdvanceRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdvanceType")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AdvanceRequests");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CEOId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyInformation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ContractStartingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EstablishedDate")
                        .HasColumnType("date");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MersisNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxIdentificaitonNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxOfficeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CEOId")
                        .IsUnique()
                        .HasFilter("[CEOId] IS NOT NULL");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyAddress = "123 Innovation Drive",
                            CompanyEmail = "contact@techinnovations.com",
                            CompanyField = "Technology",
                            CompanyInformation = "Leading tech company specializing in innovative solutions.",
                            CompanyName = "Tech Innovations",
                            CompanyPhoneNumber = "555-1234",
                            CompanyTitle = "Tech Innovations Bilişim ve Teknoloji Şirketi",
                            CompanyType = "SoleProprietorship",
                            CompanyWebsite = "www.techinnovations.com",
                            ContractEndDate = new DateOnly(1, 1, 1),
                            ContractStartingDate = new DateOnly(2020, 3, 30),
                            CreationDate = new DateTime(2024, 8, 20, 16, 18, 25, 576, DateTimeKind.Local).AddTicks(750),
                            EstablishedDate = new DateOnly(2001, 4, 23),
                            LogoPath = "/images/logos/tech_innovations.png",
                            MersisNumber = "1234567890",
                            Status = 0,
                            TaxIdentificaitonNumber = "TI123456",
                            TaxOfficeName = "Downtown Tax Office"
                        },
                        new
                        {
                            ID = 2,
                            CompanyAddress = "456 Green Road",
                            CompanyEmail = "info@greenenergy.com",
                            CompanyField = "Energy",
                            CompanyInformation = "Providing renewable energy solutions worldwide.",
                            CompanyName = "Green Energy Solutions",
                            CompanyPhoneNumber = "555-5678",
                            CompanyTitle = "Green Energy Solutions AŞ.",
                            CompanyType = "JointStockCompany",
                            CompanyWebsite = "www.greenenergy.com",
                            ContractEndDate = new DateOnly(1, 1, 1),
                            ContractStartingDate = new DateOnly(2020, 3, 30),
                            CreationDate = new DateTime(2024, 8, 20, 16, 18, 25, 576, DateTimeKind.Local).AddTicks(829),
                            EstablishedDate = new DateOnly(2010, 7, 15),
                            LogoPath = "/images/logos/greenenergy.jpeg",
                            MersisNumber = "0987654321",
                            Status = 0,
                            TaxIdentificaitonNumber = "TI654321",
                            TaxOfficeName = "Uptown Tax Office"
                        },
                        new
                        {
                            ID = 3,
                            CompanyAddress = "789 Wellness Ave",
                            CompanyEmail = "support@healthwellness.com",
                            CompanyField = "Healthcare",
                            CompanyInformation = "Committed to providing top health and wellness services.",
                            CompanyName = "Health & Wellness",
                            CompanyPhoneNumber = "555-7890",
                            CompanyTitle = "Health & Wellness Sağlık ve Güzellik Merkezi LTD.ŞTİ.",
                            CompanyType = "LimitedCompany",
                            CompanyWebsite = "www.healthwellness.com",
                            ContractEndDate = new DateOnly(1, 1, 1),
                            ContractStartingDate = new DateOnly(2020, 3, 30),
                            CreationDate = new DateTime(2024, 8, 20, 16, 18, 25, 576, DateTimeKind.Local).AddTicks(838),
                            EstablishedDate = new DateOnly(2015, 3, 30),
                            LogoPath = "/images/logos/healthandwellness.jpeg",
                            MersisNumber = "1122334455",
                            Status = 0,
                            TaxIdentificaitonNumber = "TI112233",
                            TaxOfficeName = "City Tax Office"
                        },
                        new
                        {
                            ID = 4,
                            CompanyAddress = "101 Education Blvd",
                            CompanyEmail = "admissions@edufuture.com",
                            CompanyField = "Education",
                            CompanyInformation = "Innovative education for the future.",
                            CompanyName = "EduFuture Academy",
                            CompanyPhoneNumber = "555-1011",
                            CompanyTitle = "EduFuture Eğitim Merkezi LTD.ŞTİ.",
                            CompanyType = "LimitedCompany",
                            CompanyWebsite = "www.edufuture.com",
                            ContractEndDate = new DateOnly(1, 1, 1),
                            ContractStartingDate = new DateOnly(2020, 3, 30),
                            CreationDate = new DateTime(2024, 8, 20, 16, 18, 25, 576, DateTimeKind.Local).AddTicks(846),
                            EstablishedDate = new DateOnly(2020, 1, 10),
                            LogoPath = "/images/logos/edufuture.jpeg",
                            MersisNumber = "5566778899",
                            Status = 0,
                            TaxIdentificaitonNumber = "TI556677",
                            TaxOfficeName = "Suburb Tax Office"
                        });
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Departments");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.ExpenseRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ExpenseRequests");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.LeaveRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<double>("LeaveDays")
                        .HasColumnType("float");

                    b.Property<DateOnly>("LeaveEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LeaveStartingDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "2c7a1e78-ff1d-41db-83c6-39507719ca5d",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "a2b0d0d6-cdf0-467e-8ba5-08262ee10a2e",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "4000318b-a1f7-4718-9ad0-2bf7457606e7",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CEORelatedCompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeRelatedCompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Job")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MarialStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PicturePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecondSurname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeRelatedCompanyID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Üsküdar",
                            BloodGroup = "BPositive",
                            ConcurrencyStamp = "392457ea-9392-4b03-94d0-2e79b3a96f5b",
                            CreationDate = new DateTime(2024, 8, 20, 13, 18, 25, 585, DateTimeKind.Utc).AddTicks(535),
                            Email = "onurakpinarr95@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Male",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Onur",
                            NormalizedEmail = "ONURAKPINARR95@GMAIL.COM",
                            NormalizedUserName = "ONURAKPINARR95@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFUW3yRPru+Ercqt1aHeV7ep4MU4hcghIPqIXgiJtdR8mBBuwD3+DiRqARErqBkjJQ==",
                            PhoneNumber = "+905555555555",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "4439426f-6128-44f8-85b2-c72e3ffe541d",
                            Status = 1,
                            Surname = "Akpınar",
                            TwoFactorEnabled = false,
                            UserName = "onurakpinarr95@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "Küçükyalı",
                            BloodGroup = "APositive",
                            ConcurrencyStamp = "cda56e4f-b451-44a7-a2c7-ffa4bdf64d26",
                            CreationDate = new DateTime(2024, 8, 20, 13, 18, 25, 675, DateTimeKind.Utc).AddTicks(4756),
                            Email = "sinemgngr@outlook.com",
                            EmailConfirmed = true,
                            Gender = "Female",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Sinem",
                            NormalizedEmail = "SINEMGNGR@OUTLOOK.COM",
                            NormalizedUserName = "SINEMGNGR@OUTLOOK.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEG6WA3RJdG1vOxl7PnO/T1wSMH8JjEWw5WrJpzJsCxQc9Zom5uQ+F3KK0UTctNbPUw==",
                            PhoneNumber = "+90544444444",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "af57e12b-6b44-48c8-a101-11ead09e0b3d",
                            Status = 1,
                            Surname = "Güngör",
                            TwoFactorEnabled = false,
                            UserName = "sinemgngr@outlook.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "Edirne",
                            BloodGroup = "OPositive",
                            ConcurrencyStamp = "8f620f9e-3530-4d73-82ca-94e5f65f10e6",
                            CreationDate = new DateTime(2024, 8, 20, 13, 18, 25, 765, DateTimeKind.Utc).AddTicks(3724),
                            Email = "recepoztuna@hotmail.com",
                            EmailConfirmed = true,
                            Gender = "Male",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Recep",
                            NormalizedEmail = "RECEPOZTUNA@HOTMAIL.COM",
                            NormalizedUserName = "RECEPOZTUNA@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGUiq+xY1UYKowCOxO+UF/9/uTWC5BLreAePo4LUksa7gyekShqvWalGiMJaw0Iiiw==",
                            PhoneNumber = "+905333333333",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "82c1ca49-01ae-4cba-a8f6-f2d43c328aa3",
                            Status = 1,
                            Surname = "Öztuna",
                            TwoFactorEnabled = false,
                            UserName = "recepoztuna@hotmail.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "Zeytinburnu",
                            BloodGroup = "ABPositive",
                            ConcurrencyStamp = "72b0c222-fcc9-48db-ace6-a231c029c916",
                            CreationDate = new DateTime(2024, 8, 20, 13, 18, 25, 868, DateTimeKind.Utc).AddTicks(4886),
                            Email = "ozercemre1@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Male",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Cemre",
                            NormalizedEmail = "OZERCEMRE1@GMAIL.COM",
                            NormalizedUserName = "OZERCEMRE1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEJ89H5eA3fIA+QwaijYL3oPwu+WQ92tc1CU8QGgXc8wjT8pcXHM/FvrybKjD/UiAhA==",
                            PhoneNumber = "+905311111111",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "c66b40ea-d77a-4aa1-b7ea-e7c0cc6789fc",
                            Status = 1,
                            Surname = "Admin",
                            TwoFactorEnabled = false,
                            UserName = "ozercemre1@gmail.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.AdvanceRequest", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", "Employee")
                        .WithMany("AdvanceRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Company", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", "CEO")
                        .WithOne("CEORelatedCompany")
                        .HasForeignKey("HRMaster_API_Project.Entities.Concrete.Company", "CEOId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CEO");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Department", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.ExpenseRequest", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", "Employee")
                        .WithMany("ExpenseRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.LeaveRequest", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.User", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Company", "EmployeeRelatedCompany")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRelatedCompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("EmployeeRelatedCompany");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Company", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.User", b =>
                {
                    b.Navigation("AdvanceRequests");

                    b.Navigation("CEORelatedCompany");

                    b.Navigation("ExpenseRequests");

                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
