// <auto-generated />
using System;
using HRMaster_API_Project.DAL.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HRMaster_API_Project.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240825135153_InitDB-10")]
    partial class InitDB10
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.AdvanceRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AdvanceType")
                        .HasColumnType("int");

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("AdvanceRequests");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Company", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("CEOId")
                        .HasColumnType("int");

                    b.Property<string>("CompanyAddress")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<string>("CompanyEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyInformation")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyPhoneNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("CompanyTitle")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("CompanyType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CompanyWebsite")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateOnly>("ContractEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("ContractStartingDate")
                        .HasColumnType("date");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly>("EstablishedDate")
                        .HasColumnType("date");

                    b.Property<string>("LogoPath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("MersisNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("TaxIdentificaitonNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TaxOfficeName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CEOId")
                        .IsUnique()
                        .HasFilter("[CEOId] IS NOT NULL");

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CEOId = 5,
                            CompanyAddress = "123 Innovation Drive",
                            CompanyEmail = "contact@techinnovations.com",
                            CompanyField = "Technology",
                            CompanyInformation = "Leading tech company specializing in innovative solutions.",
                            CompanyName = "Tech Innovations",
                            CompanyPhoneNumber = "555-1234",
                            CompanyTitle = "Tech Innovations Bilişim ve Teknoloji Şirketi",
                            CompanyType = "SoleProprietorship",
                            CompanyWebsite = "www.techinnovations.com",
                            ContractEndDate = new DateOnly(1, 1, 1),
                            ContractStartingDate = new DateOnly(2020, 3, 30),
                            CreationDate = new DateTime(2024, 8, 25, 16, 51, 52, 253, DateTimeKind.Local).AddTicks(2583),
                            EstablishedDate = new DateOnly(2001, 4, 23),
                            LogoPath = "/images/logos/tech_innovations.png",
                            MersisNumber = "1234567890",
                            Status = 0,
                            TaxIdentificaitonNumber = "TI123456",
                            TaxOfficeName = "Downtown Tax Office"
                        },
                        new
                        {
                            ID = 2,
                            CEOId = 6,
                            CompanyAddress = "456 Green Road",
                            CompanyEmail = "info@greenenergy.com",
                            CompanyField = "Energy",
                            CompanyInformation = "Providing renewable energy solutions worldwide.",
                            CompanyName = "Green Energy Solutions",
                            CompanyPhoneNumber = "555-5678",
                            CompanyTitle = "Green Energy Solutions AŞ.",
                            CompanyType = "JointStockCompany",
                            CompanyWebsite = "www.greenenergy.com",
                            ContractEndDate = new DateOnly(1, 1, 1),
                            ContractStartingDate = new DateOnly(2020, 3, 30),
                            CreationDate = new DateTime(2024, 8, 25, 16, 51, 52, 253, DateTimeKind.Local).AddTicks(2667),
                            EstablishedDate = new DateOnly(2010, 7, 15),
                            LogoPath = "/images/logos/greenenergy.jpeg",
                            MersisNumber = "0987654321",
                            Status = 0,
                            TaxIdentificaitonNumber = "TI654321",
                            TaxOfficeName = "Uptown Tax Office"
                        },
                        new
                        {
                            ID = 3,
                            CEOId = 7,
                            CompanyAddress = "789 Wellness Ave",
                            CompanyEmail = "support@healthwellness.com",
                            CompanyField = "Healthcare",
                            CompanyInformation = "Committed to providing top health and wellness services.",
                            CompanyName = "Health & Wellness",
                            CompanyPhoneNumber = "555-7890",
                            CompanyTitle = "Health & Wellness Sağlık ve Güzellik Merkezi LTD.ŞTİ.",
                            CompanyType = "LimitedCompany",
                            CompanyWebsite = "www.healthwellness.com",
                            ContractEndDate = new DateOnly(1, 1, 1),
                            ContractStartingDate = new DateOnly(2020, 3, 30),
                            CreationDate = new DateTime(2024, 8, 25, 16, 51, 52, 253, DateTimeKind.Local).AddTicks(2676),
                            EstablishedDate = new DateOnly(2015, 3, 30),
                            LogoPath = "/images/logos/healthandwellness.jpeg",
                            MersisNumber = "1122334455",
                            Status = 0,
                            TaxIdentificaitonNumber = "TI112233",
                            TaxOfficeName = "City Tax Office"
                        },
                        new
                        {
                            ID = 4,
                            CEOId = 8,
                            CompanyAddress = "101 Education Blvd",
                            CompanyEmail = "admissions@edufuture.com",
                            CompanyField = "Education",
                            CompanyInformation = "Innovative education for the future.",
                            CompanyName = "EduFuture Academy",
                            CompanyPhoneNumber = "555-1011",
                            CompanyTitle = "EduFuture Eğitim Merkezi LTD.ŞTİ.",
                            CompanyType = "LimitedCompany",
                            CompanyWebsite = "www.edufuture.com",
                            ContractEndDate = new DateOnly(1, 1, 1),
                            ContractStartingDate = new DateOnly(2020, 3, 30),
                            CreationDate = new DateTime(2024, 8, 25, 16, 51, 52, 253, DateTimeKind.Local).AddTicks(2682),
                            EstablishedDate = new DateOnly(2020, 1, 10),
                            LogoPath = "/images/logos/edufuture.jpeg",
                            MersisNumber = "5566778899",
                            Status = 0,
                            TaxIdentificaitonNumber = "TI556677",
                            TaxOfficeName = "Suburb Tax Office"
                        });
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Department", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("CompanyID")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DepartmentName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("CompanyID");

                    b.ToTable("Departments");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            CompanyID = 1,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "İnsan Kaynakları",
                            Status = 0
                        },
                        new
                        {
                            ID = 2,
                            CompanyID = 1,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Finans",
                            Status = 0
                        },
                        new
                        {
                            ID = 3,
                            CompanyID = 1,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Pazarlama",
                            Status = 0
                        },
                        new
                        {
                            ID = 4,
                            CompanyID = 1,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Teknoloji",
                            Status = 0
                        },
                        new
                        {
                            ID = 5,
                            CompanyID = 1,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Satış",
                            Status = 0
                        },
                        new
                        {
                            ID = 6,
                            CompanyID = 1,
                            CreationDate = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            DepartmentName = "Mühendislik",
                            Status = 0
                        });
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.ExpenseRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<int>("ExpenseType")
                        .HasColumnType("int");

                    b.Property<string>("FilePath")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("ExpenseRequests");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.LeaveRequest", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ApprovalStatus")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("EmployeeID")
                        .HasColumnType("int");

                    b.Property<double>("LeaveDays")
                        .HasColumnType("float");

                    b.Property<DateOnly>("LeaveEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("LeaveStartingDate")
                        .HasColumnType("date");

                    b.Property<int>("LeaveType")
                        .HasColumnType("int");

                    b.Property<DateTime>("RequestDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ResponseDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("ID");

                    b.HasIndex("EmployeeID");

                    b.ToTable("LeaveRequests");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Role", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ConcurrencyStamp = "e7423cba-344b-4a22-9ae9-60ac841b8afc",
                            Name = "SuperAdmin",
                            NormalizedName = "SUPERADMIN"
                        },
                        new
                        {
                            Id = 2,
                            ConcurrencyStamp = "313d1bdd-0d8a-409e-916c-7d33f3f1d006",
                            Name = "Manager",
                            NormalizedName = "MANAGER"
                        },
                        new
                        {
                            Id = 4,
                            ConcurrencyStamp = "9533dd53-8d5f-422a-9ad4-6875b6955324",
                            Name = "Employee",
                            NormalizedName = "EMPLOYEE"
                        });
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("Address")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<DateOnly?>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("BirthState")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("BloodGroup")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<int?>("CEORelatedCompanyID")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("DepartmentID")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<int?>("EmployeeRelatedCompanyID")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateOnly?>("HireDate")
                        .HasColumnType("date");

                    b.Property<string>("IdentityNumber")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Job")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("MarialStatus")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("PicturePath")
                        .HasMaxLength(500)
                        .HasColumnType("varchar");

                    b.Property<decimal?>("Salary")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SecondName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecondSurname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateOnly?>("TerminationDate")
                        .HasColumnType("date");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("DepartmentID");

                    b.HasIndex("EmployeeRelatedCompanyID");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccessFailedCount = 0,
                            Address = "Üsküdar",
                            BirthDate = new DateOnly(1986, 3, 15),
                            BirthState = "Bolu",
                            BloodGroup = "BPositive",
                            ConcurrencyStamp = "7e666d23-2da7-4ee6-a281-a551ed9421d2",
                            CreationDate = new DateTime(2024, 8, 25, 13, 51, 52, 259, DateTimeKind.Utc).AddTicks(9887),
                            Email = "onurakpinarr95@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Male",
                            HireDate = new DateOnly(2019, 11, 1),
                            IdentityNumber = "56789012345",
                            Job = "ADMIN",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Onur",
                            NormalizedEmail = "ONURAKPINARR95@GMAIL.COM",
                            NormalizedUserName = "ONURAKPINARR95@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEEEYNPYORbRqwKvNGwsG3j7Aq6JQSq0sIQ+PazRdmlslA+ROol0LykJSZVuxWDB6+w==",
                            PhoneNumber = "+905555555555",
                            PhoneNumberConfirmed = false,
                            PicturePath = "default-avatar.jpg",
                            Salary = 8700.5m,
                            SecurityStamp = "cbe50fda-7294-49f0-ae9f-77be669264f7",
                            Status = 1,
                            Surname = "Akpınar",
                            Title = "Project Manager",
                            TwoFactorEnabled = false,
                            UserName = "onurakpinarr95@gmail.com"
                        },
                        new
                        {
                            Id = 2,
                            AccessFailedCount = 0,
                            Address = "Küçükyalı",
                            BirthDate = new DateOnly(1985, 6, 20),
                            BirthState = "Gaziantep",
                            BloodGroup = "APositive",
                            ConcurrencyStamp = "831d8f4a-48f1-41c4-9eee-8a9f87658a3f",
                            CreationDate = new DateTime(2024, 8, 25, 13, 51, 52, 328, DateTimeKind.Utc).AddTicks(6529),
                            Email = "sinemgngr@outlook.com",
                            EmailConfirmed = true,
                            Gender = "Female",
                            HireDate = new DateOnly(2020, 7, 15),
                            IdentityNumber = "57890123456",
                            Job = "ADMIN",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Sinem",
                            NormalizedEmail = "SINEMGNGR@OUTLOOK.COM",
                            NormalizedUserName = "SINEMGNGR@OUTLOOK.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEFtb6yUR1GpE+lnh9FdmCMJJjGORzqYeLHLWglHuIEB9IdyCzX5iFRuRXy2i/GbBJw==",
                            PhoneNumber = "+90544444444",
                            PhoneNumberConfirmed = false,
                            PicturePath = "default-avatar.jpg",
                            Salary = 7900m,
                            SecurityStamp = "4b1dbf86-db23-4bc0-9b6a-c6777d605507",
                            Status = 1,
                            Surname = "Güngör",
                            Title = "Business Analyst",
                            TwoFactorEnabled = false,
                            UserName = "sinemgngr@outlook.com"
                        },
                        new
                        {
                            Id = 3,
                            AccessFailedCount = 0,
                            Address = "Edirne",
                            BirthDate = new DateOnly(1992, 10, 5),
                            BirthState = "Mardin",
                            BloodGroup = "OPositive",
                            ConcurrencyStamp = "8fabdfbd-6dfb-41cd-9acb-f1cc599e3b29",
                            CreationDate = new DateTime(2024, 8, 25, 13, 51, 52, 401, DateTimeKind.Utc).AddTicks(6021),
                            Email = "recepoztuna@hotmail.com",
                            EmailConfirmed = true,
                            Gender = "Male",
                            HireDate = new DateOnly(2021, 3, 1),
                            IdentityNumber = "58901234567",
                            Job = "ADMINt",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Recep",
                            NormalizedEmail = "RECEPOZTUNA@HOTMAIL.COM",
                            NormalizedUserName = "RECEPOZTUNA@HOTMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHvuq8qAHf77vfivK4HxpAoNQXbyVPLx5wd+P0P/czOe6xetiRceXLgiSvrfQpfgfw==",
                            PhoneNumber = "+905333333333",
                            PhoneNumberConfirmed = false,
                            PicturePath = "default-avatar.jpg",
                            Salary = 7300.25m,
                            SecurityStamp = "5dbae324-622d-4550-885e-a53ea6c8e472",
                            Status = 1,
                            Surname = "Öztuna",
                            Title = "Digital Marketing Specialist",
                            TwoFactorEnabled = false,
                            UserName = "recepoztuna@hotmail.com"
                        },
                        new
                        {
                            Id = 4,
                            AccessFailedCount = 0,
                            Address = "Zeytinburnu",
                            BirthDate = new DateOnly(1992, 10, 5),
                            BirthState = "Mardin",
                            BloodGroup = "ABPositive",
                            ConcurrencyStamp = "da1ba44b-11a7-4dfa-98ec-8a9ee6a3cb3d",
                            CreationDate = new DateTime(2024, 8, 25, 13, 51, 52, 477, DateTimeKind.Utc).AddTicks(280),
                            Email = "ozercemre1@gmail.com",
                            EmailConfirmed = true,
                            Gender = "Male",
                            HireDate = new DateOnly(2021, 3, 1),
                            IdentityNumber = "58901234567",
                            Job = "ADMIN",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Cemre",
                            NormalizedEmail = "OZERCEMRE1@GMAIL.COM",
                            NormalizedUserName = "OZERCEMRE1@GMAIL.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEGjsXiLxsmyP7FnCJYTz6qA01EiN4DpC0hCoB1mOz+vFwHZag9GvMqBX4ycshjPErQ==",
                            PhoneNumber = "+905311111111",
                            PhoneNumberConfirmed = false,
                            PicturePath = "default-avatar.jpg",
                            Salary = 7300.25m,
                            SecurityStamp = "5d47b98e-b000-4987-a2f4-97c0fbbe9c4e",
                            Status = 1,
                            Surname = "Admin",
                            Title = "Digital Marketing Specialist",
                            TwoFactorEnabled = false,
                            UserName = "ozercemre1@gmail.com"
                        },
                        new
                        {
                            Id = 5,
                            AccessFailedCount = 0,
                            Address = "Kadıköy",
                            BirthDate = new DateOnly(1992, 11, 10),
                            BirthState = "Bursa",
                            BloodGroup = "APositive",
                            CEORelatedCompanyID = 1,
                            ConcurrencyStamp = "370656d3-0174-44e8-bbdf-0956e9e70a24",
                            CreationDate = new DateTime(2024, 8, 25, 13, 51, 52, 556, DateTimeKind.Utc).AddTicks(515),
                            Email = "ali.yilmaz@example.com",
                            EmailConfirmed = true,
                            Gender = "Male",
                            HireDate = new DateOnly(2020, 10, 1),
                            IdentityNumber = "43212345312",
                            Job = "CEO",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Ali",
                            NormalizedEmail = "ALI.YILMAZ@EXAMPLE.COM",
                            NormalizedUserName = "ALI.YILMAZ@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEBubfUXhB/Gql3fM9sbPk7RpbalPeMX2So+tRBHVMySc1shAV/vGwKNYY61ilXF7Gw==",
                            PhoneNumber = "+905311234567",
                            PhoneNumberConfirmed = false,
                            PicturePath = "default-avatar.jpg",
                            Salary = 8700.25m,
                            SecurityStamp = "a0fcbca9-8a19-41d0-99d7-be2426589525",
                            Status = 1,
                            Surname = "Yılmaz",
                            Title = "HR Manager",
                            TwoFactorEnabled = false,
                            UserName = "ali.yilmaz@example.com"
                        },
                        new
                        {
                            Id = 6,
                            AccessFailedCount = 0,
                            Address = "Beşiktaş",
                            BirthDate = new DateOnly(1985, 5, 20),
                            BirthState = "İstanbul",
                            BloodGroup = "BNegative",
                            CEORelatedCompanyID = 2,
                            ConcurrencyStamp = "bbf4f262-6f2e-4add-ae33-f0fd8293a481",
                            CreationDate = new DateTime(2024, 8, 25, 13, 51, 52, 644, DateTimeKind.Utc).AddTicks(4015),
                            Email = "ayse.demir@example.com",
                            EmailConfirmed = true,
                            Gender = "Female",
                            HireDate = new DateOnly(2018, 6, 15),
                            IdentityNumber = "53245678901",
                            Job = "CEO",
                            LockoutEnabled = false,
                            MarialStatus = "Married",
                            Name = "Ayşe",
                            NormalizedEmail = "AYSE.DEMIR@EXAMPLE.COM",
                            NormalizedUserName = "AYSE.DEMIR@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEKSuqUoVP6U5hBVVqQLFdm9TsFEYTuR08niSoIO4SUN2ab66xrQb8/+4MDk+6CSSRw==",
                            PhoneNumber = "+905322345678",
                            PhoneNumberConfirmed = false,
                            PicturePath = "default-avatar.jpg",
                            Salary = 9200.75m,
                            SecurityStamp = "0d2aea6c-12fd-45d3-b230-267ea7fe922e",
                            Status = 1,
                            Surname = "Demir",
                            Title = "Chief Technology Officer",
                            TwoFactorEnabled = false,
                            UserName = "ayse.demir@example.com"
                        },
                        new
                        {
                            Id = 7,
                            AccessFailedCount = 0,
                            Address = "Üsküdar",
                            BirthDate = new DateOnly(1978, 8, 30),
                            BirthState = "Ankara",
                            BloodGroup = "ANegative",
                            CEORelatedCompanyID = 3,
                            ConcurrencyStamp = "e105bda8-efc2-422d-be09-021ed1527f43",
                            CreationDate = new DateTime(2024, 8, 25, 13, 51, 52, 719, DateTimeKind.Utc).AddTicks(2047),
                            Email = "mehmet.kaya@example.com",
                            EmailConfirmed = true,
                            Gender = "Male",
                            HireDate = new DateOnly(2016, 2, 10),
                            IdentityNumber = "32145698700",
                            Job = "CFO",
                            LockoutEnabled = false,
                            MarialStatus = "Single",
                            Name = "Mehmet",
                            NormalizedEmail = "MEHMET.KAYA@EXAMPLE.COM",
                            NormalizedUserName = "MEHMET.KAYA@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEIz1qJScLwraUoAa/GyLuJpA97vrTK4qKD2H0eoIy+7lri9+r8+lLT8zBwKZwBfuhA==",
                            PhoneNumber = "+905336789012",
                            PhoneNumberConfirmed = false,
                            PicturePath = "default-avatar.jpg",
                            Salary = 9500.5m,
                            SecurityStamp = "a780f350-3bc0-422d-8617-49e87efb1dfe",
                            Status = 1,
                            Surname = "Kaya",
                            Title = "Chief Financial Officer",
                            TwoFactorEnabled = false,
                            UserName = "mehmet.kaya@example.com"
                        },
                        new
                        {
                            Id = 8,
                            AccessFailedCount = 0,
                            Address = "Taksim",
                            BirthDate = new DateOnly(1990, 12, 5),
                            BirthState = "İzmir",
                            BloodGroup = "ONegative",
                            CEORelatedCompanyID = 4,
                            ConcurrencyStamp = "cf888ebb-f408-4aee-b799-02f0ae9788c6",
                            CreationDate = new DateTime(2024, 8, 25, 13, 51, 52, 795, DateTimeKind.Utc).AddTicks(8432),
                            Email = "fatma.yurt@example.com",
                            EmailConfirmed = true,
                            Gender = "Female",
                            HireDate = new DateOnly(2019, 11, 22),
                            IdentityNumber = "45678901234",
                            Job = "COO",
                            LockoutEnabled = false,
                            MarialStatus = "Married",
                            Name = "Fatma",
                            NormalizedEmail = "FATMA.YURT@EXAMPLE.COM",
                            NormalizedUserName = "FATMA.YURT@EXAMPLE.COM",
                            PasswordHash = "AQAAAAIAAYagAAAAEHkLJ7sPtepjqh2+gRnzP7laC+LTXckegLf0U/DjxB0/Wj9ssKLQGKv0ssORhaZZxQ==",
                            PhoneNumber = "+905349876543",
                            PhoneNumberConfirmed = false,
                            PicturePath = "default-avatar.jpg",
                            Salary = 8800m,
                            SecurityStamp = "41981f88-344e-4b9e-a64f-24da21b7d5dc",
                            Status = 1,
                            Surname = "Yurt",
                            Title = "Chief Operating Officer",
                            TwoFactorEnabled = false,
                            UserName = "fatma.yurt@example.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<int>("RoleId")
                        .HasColumnType("int");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = 1,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 2,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 3,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 4,
                            RoleId = 1
                        },
                        new
                        {
                            UserId = 5,
                            RoleId = 2
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.AdvanceRequest", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", "Employee")
                        .WithMany("AdvanceRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Company", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", "CEO")
                        .WithOne("CEORelatedCompany")
                        .HasForeignKey("HRMaster_API_Project.Entities.Concrete.Company", "CEOId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("CEO");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Department", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Company", "Company")
                        .WithMany("Departments")
                        .HasForeignKey("CompanyID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.ExpenseRequest", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", "Employee")
                        .WithMany("ExpenseRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.LeaveRequest", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", "Employee")
                        .WithMany("LeaveRequests")
                        .HasForeignKey("EmployeeID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.User", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Department", "Department")
                        .WithMany("Employees")
                        .HasForeignKey("DepartmentID")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Company", "EmployeeRelatedCompany")
                        .WithMany("Employees")
                        .HasForeignKey("EmployeeRelatedCompanyID")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Department");

                    b.Navigation("EmployeeRelatedCompany");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.Role", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<int>", b =>
                {
                    b.HasOne("HRMaster_API_Project.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Company", b =>
                {
                    b.Navigation("Departments");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.Department", b =>
                {
                    b.Navigation("Employees");
                });

            modelBuilder.Entity("HRMaster_API_Project.Entities.Concrete.User", b =>
                {
                    b.Navigation("AdvanceRequests");

                    b.Navigation("CEORelatedCompany");

                    b.Navigation("ExpenseRequests");

                    b.Navigation("LeaveRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
